language: python
python:
  - "3.7"
git:
  depth: false
jobs:
  include:
    - install:
        - pip install -r requirements.txt
        - pip install codecov
        - pip install coveralls
      script: coverage run -m unittest
      after_success:
        - codecov
        - coveralls
    - install:
        - pip install -r requirements-dev.txt
      script: flake8
    - install:
        - pip install -r requirements-dev.txt
      script: pylint colonel
    - install:
        - pip install -r requirements-dev.txt
      script: mypy -p colonel


# FIXME: workaround for Python 3.7
# see:
#   https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
#   https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial
sudo: required
